## ArgoCD will do initial deploy of this secret, then it'll ignore the drift that will occur manually in OpenShift.
## Drift ignore will only be for content inside of .env
kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Values.app_name }}-{{ $.Values.env }}-appenv
stringData:
  {{- range $key, $value := .Values.appEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
type: Opaque