{{ if .Values.autoscaling.enabled }}
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: {{ .Values.app_name }}-{{ .Values.env }}-hpa
spec:
  scaleTargetRef:
    kind: Deployment
    name: {{ .Values.app_name }}-{{ .Values.env }}
    apiVersion: apps/v1
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
{{ end }}