apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-ai-app-backend # Recreate for each app. Including the other 2 frontends.
  namespace: openshift-gitops
spec:
  destination:
    namespace: <NAMESPACE>
    server: 'https://kubernetes.default.svc'
  project: <PROJECT>
  source:
    helm:
      valueFiles:
        - values-backend.yaml # Update for each app. Including the other 2 frontends.
    path: helm
    repoURL: '<GITREPO>'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
      - kind: Secret
        name: <SECRET_NAME>
        jsonPointers:
          - /data/.env